### ISSUE TITLE
Removing contours/outlines

### ISSUE THREAD

**Issue by Magique-6** [ashonit/DND-5e-LaTeX-Template#15]
Hey, I love the package. Sorry if this sounds like a newbie question. Is there a way to remove the outline around Part and Chapter font?

**Comment by ashonit** [comment]
Hi Magique-6, github wasn't emailing me notifications so only just saw this sorry. I'll have a look and see if I can figure it out.

**Comment by ashonit** [comment]
Added option 'nooutline' to remove the outlines around title/chapter fonts
